* Encoding: UTF-8.

WEIGHT BY weight.


CROSSTABS
  /TABLES=q1 q2 BY q6
  /FORMAT=AVALUE TABLES
  /CELLS=COUNT COLUMN
  /COUNT ROUND CELL.

T-TEST GROUPS=q6(1 2)
  /MISSING=ANALYSIS
  /VARIABLES=q1_reverse_coded q2_reverse_coded
  /CRITERIA=CI(.95).

CROSSTABS
  /TABLES=q1 q2 BY employ
  /FORMAT=AVALUE TABLES
  /CELLS=COUNT COLUMN
  /COUNT ROUND CELL.

ONEWAY q1_reverse_coded q2_reverse_coded BY employ
  /STATISTICS DESCRIPTIVES
  /MISSING ANALYSIS
  /POSTHOC=BONFERRONI ALPHA(0.05).

CROSSTABS
  /TABLES=q1 q2 BY q14
  /FORMAT=AVALUE TABLES
  /CELLS=COUNT COLUMN
  /COUNT ROUND CELL.

CROSSTABS
  /TABLES=q1 q2 BY gender_client
  /FORMAT=AVALUE TABLES
  /CELLS=COUNT COLUMN
  /COUNT ROUND CELL.

T-TEST GROUPS=gender_client(1 2)
  /MISSING=ANALYSIS
  /VARIABLES=q1_reverse_coded q2_reverse_coded
  /CRITERIA=CI(.95).

CROSSTABS
  /TABLES=q1 q2 BY race
  /FORMAT=AVALUE TABLES
  /CELLS=COUNT COLUMN
  /COUNT ROUND CELL.

CROSSTABS
  /TABLES=q1 q2 BY educ
  /FORMAT=AVALUE TABLES
  /CELLS=COUNT COLUMN
  /COUNT ROUND CELL.

CORRELATIONS
  /VARIABLES=q1_reverse_coded q2_reverse_coded educ
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.


ONEWAY q1_reverse_coded q2_reverse_coded BY educ
  /STATISTICS DESCRIPTIVES
  /MISSING ANALYSIS
  /POSTHOC=BONFERRONI ALPHA(0.05).


CROSSTABS
  /TABLES=q1 q2 BY marstat
  /FORMAT=AVALUE TABLES
  /CELLS=COUNT COLUMN
  /COUNT ROUND CELL.

ONEWAY q1_reverse_coded q2_reverse_coded BY marstat
  /STATISTICS DESCRIPTIVES
  /MISSING ANALYSIS
  /POSTHOC=BONFERRONI ALPHA(0.05).

CROSSTABS
  /TABLES=q1 q2 BY pid3
  /FORMAT=AVALUE TABLES
  /CELLS=COUNT COLUMN
  /COUNT ROUND CELL.



ONEWAY q1_reverse_coded q2_reverse_coded BY pid3
  /STATISTICS DESCRIPTIVES
  /MISSING ANALYSIS
  /POSTHOC=BONFERRONI ALPHA(0.05).


CROSSTABS
  /TABLES=q1 q2 BY pid7
  /FORMAT=AVALUE TABLES
  /CELLS=COUNT COLUMN
  /COUNT ROUND CELL.


ONEWAY q1_reverse_coded q2_reverse_coded BY pid7
  /STATISTICS DESCRIPTIVES
  /MISSING ANALYSIS
  /POSTHOC=BONFERRONI ALPHA(0.05).

CROSSTABS
  /TABLES=q1 q2 BY presvote16post
  /FORMAT=AVALUE TABLES
  /CELLS=COUNT COLUMN
  /COUNT ROUND CELL.

CROSSTABS
  /TABLES=q1 q2 BY ideo5
  /FORMAT=AVALUE TABLES
  /CELLS=COUNT
  /COUNT ROUND CELL.

ONEWAY q1_reverse_coded q2_reverse_coded BY ideo5
  /STATISTICS DESCRIPTIVES
  /MISSING ANALYSIS
  /POSTHOC=BONFERRONI ALPHA(0.05).



CORRELATIONS
  /VARIABLES=newsint_reverse_coded q1_reverse_coded q2_reverse_coded
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.


CROSSTABS
  /TABLES=q1 q2 BY religpew pew_churatd pew_bornagain pew_religimp pew_prayer
  /FORMAT=AVALUE TABLES
  /CELLS=COUNT
  /COUNT ROUND CELL.

ONEWAY q1_reverse_coded q2_reverse_coded BY religpew
  /STATISTICS DESCRIPTIVES
  /MISSING ANALYSIS
  /POSTHOC=BONFERRONI ALPHA(0.05).

ONEWAY q1_reverse_coded q2_reverse_coded BY pew_churatd
  /STATISTICS DESCRIPTIVES
  /MISSING ANALYSIS
  /POSTHOC=BONFERRONI ALPHA(0.05).

ONEWAY q1_reverse_coded q2_reverse_coded BY pew_bornagain
  /STATISTICS DESCRIPTIVES
  /MISSING ANALYSIS
  /POSTHOC=BONFERRONI ALPHA(0.05).

ONEWAY q1_reverse_coded q2_reverse_coded BY pew_religimp
  /STATISTICS DESCRIPTIVES
  /MISSING ANALYSIS
  /POSTHOC=BONFERRONI ALPHA(0.05).

ONEWAY q1_reverse_coded q2_reverse_coded BY pew_prayer
  /STATISTICS DESCRIPTIVES
  /MISSING ANALYSIS
  /POSTHOC=BONFERRONI ALPHA(0.05).

CORRELATIONS
  /VARIABLES=q1_reverse_coded q2_reverse_coded Age
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CROSSTABS
  /TABLES=q1 q2 BY faminc_new
  /FORMAT=AVALUE TABLES
  /CELLS=COUNT
  /COUNT ROUND CELL.

USE ALL.
COMPUTE filter_$=(faminc_new <= 13).
VARIABLE LABELS filter_$ 'faminc_new <= 13 (FILTER)'.
VALUE LABELS filter_$ 0 'Not Selected' 1 'Selected'.
FORMATS filter_$ (f1.0).
FILTER BY filter_$.
EXECUTE.

ONEWAY q1_reverse_coded q2_reverse_coded BY faminc_new
  /STATISTICS DESCRIPTIVES
  /MISSING ANALYSIS
  /POSTHOC=BONFERRONI ALPHA(0.05).

CORRELATIONS
  /VARIABLES=q1_reverse_coded q2_reverse_coded faminc_new
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.
